### PR TITLE
TEST: Initial Implementation of Actions and Template Workflows

### PR DESCRIPTION
**Pull request by CurroRodriguez**

### CODE REVIEW

**Comment by CurroRodriguez** [comment]
@arahmanhamdy @dekay2001 Do not merge this PR because I'm using it for testing. I'll let you know when you can merge it.

**Comment by CurroRodriguez** [comment]
@dekay2001 Let's see if you get notified in Teams.

**Comment by CurroRodriguez** [comment]
@dekay2001 Another notifications test.

**Comment by CurroRodriguez** [comment]
@arahmanhamdy @dekay2001 You can code review this PR now and merge the PR when ready. Also, you can delete the branch.

**Comment by CurroRodriguez** [comment]
> @arahmanhamdy @dekay2001 You can code review this PR now and merge the PR when ready. Also, you can delete the branch.

Wait until I document the actions.

**Comment by CurroRodriguez** [comment]
@dekay2001 @arahmanhamdy This PR is ready for review.

**Review by dekay2001 — APPROVED** [review]

**Review by arahmanhamdy — APPROVED** [review]

**Pull request merged**
